// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP7Z4wF1PlC9Mx1Jvyp0XpUO6oZc5d0ls',
    appId: '1:234707663858:web:c64f7a5c837b64eab8096b',
    messagingSenderId: '234707663858',
    projectId: 'hopehome-51540',
    authDomain: 'hopehome-51540.firebaseapp.com',
    storageBucket: 'hopehome-51540.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuPQ1BMyuJg1omiQhvS4O6aTh_Ni8DW98',
    appId: '1:234707663858:android:4a47849ac96d5c09b8096b',
    messagingSenderId: '234707663858',
    projectId: 'hopehome-51540',
    storageBucket: 'hopehome-51540.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYSsYMr_HhcP0lXY2JuIoKjvPP874or5M',
    appId: '1:234707663858:ios:91afacd24f0cba53b8096b',
    messagingSenderId: '234707663858',
    projectId: 'hopehome-51540',
    storageBucket: 'hopehome-51540.firebasestorage.app',
    iosBundleId: 'com.example.q4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYSsYMr_HhcP0lXY2JuIoKjvPP874or5M',
    appId: '1:234707663858:ios:91afacd24f0cba53b8096b',
    messagingSenderId: '234707663858',
    projectId: 'hopehome-51540',
    storageBucket: 'hopehome-51540.firebasestorage.app',
    iosBundleId: 'com.example.q4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP7Z4wF1PlC9Mx1Jvyp0XpUO6oZc5d0ls',
    appId: '1:234707663858:web:b63b1c5c74a5d0e6b8096b',
    messagingSenderId: '234707663858',
    projectId: 'hopehome-51540',
    authDomain: 'hopehome-51540.firebaseapp.com',
    storageBucket: 'hopehome-51540.firebasestorage.app',
  );
}
